### ISSUE TITLE
开启消息分组后只浮动通知第一条消息

### ISSUE THREAD

**Issue by chinen95** [acaoairy/QQNotfAndShare#2]
RT

**Comment by ekibun** [comment]
诶miui好像不支持bundled notification，新push增加了设置项

**Comment by chinen95** [comment]
是nexus stock 7.1 不是adui 具体问题是 通知列表中有新消息预览 但是每收一条新消息 都浮动通知第一条消息

**Comment by ekibun** [comment]
浮动通知和bundled notification好像不是很兼容，但是默认应该是浮动通知最新的一条消息吧
